version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        - GIT_URL=${GIT_URL}
    volumes:
      - ./src:/app:cached
      - /app/node_modules
      - static_content:/app/dist
    ports:
      - "${DEV_PORT}:4000"
    environment:
      - NODE_ENV=development
      - GIT_URL=${GIT_URL}
    networks:
      - app-network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    volumes:
      - static_content:/usr/share/nginx/html:ro
      - ./docker/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  static_content: